celebrities = [
    {"name": "Cristiano Ronaldo", "followers": "625M", "profession": "Footballer", "country": "Portugal"},
    {"name": "Kylie Jenner", "followers": "400M", "profession": "Entrepreneur", "country": "USA"},
    {"name": "Virat Kohli", "followers": "270M", "profession": "Cricketer", "country": "India"},
    {"name": "Beyoncé", "followers": "320M", "profession": "Singer", "country": "USA"},
    {"name": "Lionel Messi", "followers": "505M", "profession": "Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "followers": "430M", "profession": "Singer", "country": "USA"},
    {"name": "Kim Kardashian", "followers": "360M", "profession": "Entrepreneur", "country": "USA"},
    {"name": "Narendra Modi", "followers": "90M", "profession": "Politician", "country": "India"},
    {"name": "Taylor Swift", "followers": "320M", "profession": "Singer", "country": "USA"},
    {"name": "Justin Bieber", "followers": "294M", "profession": "Singer", "country": "Canada"},
    {"name": "Dwayne Johnson", "followers": "393M", "profession": "Actor and Wrestler", "country": "USA"},
    {"name": "Ariana Grande", "followers": "375M", "profession": "Singer, Actress", "country": "USA"},
    {"name": "Khloé Kardashian", "followers": "303M", "profession": "Media Personality", "country": "USA"},
    {"name": "Kendall Jenner", "followers": "286M", "profession": "Media Personality", "country": "USA"},
    {"name": "Jennifer Lopez", "followers": "247M", "profession": "Singer and Actress", "country": "USA"},
    {"name": "Neymar Jr.", "followers": "231M", "profession": "Footballer", "country": "Brazil"},
    {"name": "Nicki Minaj", "followers": "224M", "profession": "Singer", "country": "Trinidad and Tobago"},
    {"name": "Kourtney Kardashian", "followers": "217M", "profession": "Media Personality", "country": "USA"},
    {"name": "Miley Cyrus", "followers": "212M", "profession": "Singer, Actress", "country": "USA"},
    {"name": "Katy Perry", "followers": "203M", "profession": "Singer", "country": "USA"},
    {"name": "Zendaya", "followers": "178M", "profession": "Actress, Singer", "country": "USA"},
    {"name": "Kevin Hart", "followers": "176M", "profession": "Comedian, Actor", "country": "USA"},
    {"name": "Cardi B", "followers": "163M", "profession": "Singer", "country": "USA"},
    {"name": "LeBron James", "followers": "159M", "profession": "Basketball Player", "country": "USA"},
    {"name": "Rihanna", "followers": "149M", "profession": "Singer", "country": "Barbados"},
    {"name": "Chrissy Teigen", "followers": "42M", "profession": "Model, TV Personality", "country": "USA"},
    {"name": "Priyanka Chopra", "followers": "91M", "profession": "Actress, Singer", "country": "India"},
    {"name": "Shakira", "followers": "90M", "profession": "Singer", "country": "Colombia"},
    {"name": "Shahid Kapoor", "followers": "46M", "profession": "Actor", "country": "India"},
    {"name": "Zlatan Ibrahimović", "followers": "67M", "profession": "Footballer", "country": "Sweden"},
    {"name": "Deepika Padukone", "followers": "83M", "profession": "Actress", "country": "India"},
    {"name": "Anushka Sharma", "followers": "68M", "profession": "Actress, Producer", "country": "India"},
    {"name": "Dua Lipa", "followers": "89M", "profession": "Singer", "country": "UK"},
    {"name": "David Beckham", "followers": "89M", "profession": "Footballer", "country": "UK"},
    {"name": "Billie Eilish", "followers": "112M", "profession": "Singer", "country": "USA"},
    {"name": "Demi Lovato", "followers": "153M", "profession": "Musician, Actress", "country": "USA"},
    {"name": "Chris Brown", "followers": "144M", "profession": "Musician", "country": "USA"},
    {"name": "Drake", "followers": "142M", "profession": "Musician", "country": "Canada"},
    {"name": "Ellen DeGeneres", "followers": "135M", "profession": "Comedian, Television Personality", "country": "USA"},
    {"name": "Kylian Mbappe", "followers": "125M", "profession": "Footballer", "country": "France"},
    {"name": "Gal Gadot", "followers": "108M", "profession": "Actress, Model", "country": "Israel"},
    {"name": "Lisa", "followers": "106M", "profession": "Musician", "country": "Thailand"},
    {"name": "Vin Diesel", "followers": "103M", "profession": "Actor", "country": "USA"},
    {"name": "Shraddha Kapoor", "followers": "94M", "profession": "Actress", "country": "India"},
    {"name": "Jennie", "followers": "88M", "profession": "Singer, Rapper", "country": "South Korea"},
    {"name": "Alia Bhatt", "followers": "86M", "profession": "Actress", "country": "India"},
    {"name": "Rose", "followers": "84M", "profession": "Singer", "country": "New Zealand"},
    {"name": "Katrina Kaif", "followers": "80M", "profession": "Actress", "country": "India"},
    {"name": "Will Smith", "followers": "70M", "profession": "Actor, Musician", "country": "USA"},
    {"name": "Salman Khan", "followers": "70M", "profession": "Actor", "country": "India"}
]
